name: Heighliner Build

on:
  push:
    branches:
      - main
      - 'froch/*'
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  heighliner:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest

    steps:

      - name: checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: container-login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Heighliner image
        id: heighliner
        uses: burnt-labs/heighliner-action@v1.0.0-alpha10
        with:
          local: true
          tag: latest
          chain: xion
          github-organization: burnt-labs
          github-repo: xion
          dockerfile: cosmos
          build-target: make install
          binaries: '["/go/bin/xiond"]'
          build-env: '["BUILD_TAGS=muslc"]'

      - name: Push Heighliner image
        run: |
          docker tag ${{ steps.heighliner.outputs.tag }} ghcr.io/burnt-labs/xion/${{ steps.heighliner.outputs.tag }}
          docker push ghcr.io/burnt-labs/xion/${{ steps.heighliner.outputs.tag }}
