name: Create Release and Publish Binary

on:
  push:
    branches:
      - froch/version
    tags:
      - '*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    environment: CI

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata for docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: burntnetwork/xion
          tags: |
            type=semver,pattern={{version}},priority=1000
            type=sha,priority=700

      - name: Build docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          target: xion-release

      - name: Copy xiond binary from container
        id: copy-binary
        run: |
          docker create --name temp_container $(echo ${{ steps.meta.outputs.tags }} | awk '{print $1}')
          docker cp temp_container:/usr/bin/xiond ./xiond-linux-amd64
          ./xiond-linux-amd64 version --long
          docker rm -v temp_container

      - name: Create and Update Release
        id: create-release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          draft: true
          prerelease: true
          artifacts: ./xiond-linux-amd64
          artifactContentType: application/octet-stream
          tag: ${{ github.ref }}
          token: ${{ secrets.GH_RELEASE_TOKEN }}
          name: Release ${{ github.ref }}
